// <auto-generated />
using System;
using LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924084051_Migrations")]
    partial class Migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            AvailableCopies = 5,
                            CategoryId = 1,
                            Price = 10.99m,
                            PublishedYear = 1925,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            AvailableCopies = 3,
                            CategoryId = 2,
                            Price = 12.99m,
                            PublishedYear = 1960,
                            Title = "To Kill a Mockingbird"
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.BorrowRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2026, 9, 24, 11, 40, 50, 910, DateTimeKind.Local).AddTicks(4128));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2026, 9, 24, 11, 40, 50, 910, DateTimeKind.Local).AddTicks(5476),
                            MemberId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowDate = new DateTime(2026, 9, 24, 11, 40, 50, 910, DateTimeKind.Local).AddTicks(5492),
                            MemberId = 2
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Classic"
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nada@gmail.com",
                            FullName = "Nada Safaa",
                            PhoneNumber = "01000000000"
                        },
                        new
                        {
                            Id = 2,
                            Email = "belal@gmail.com",
                            FullName = "Belal Mohamed",
                            PhoneNumber = "01100000000"
                        });
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Book", b =>
                {
                    b.HasOne("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.BorrowRecord", b =>
                {
                    b.HasOne("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Member", "Member")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LIBRARY_MANAGEMENT_SYSTEM__LMS__CaseStudy1.Models.Member", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
